//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.additional = new HashSet<additional>();
            this.reservation = new HashSet<reservation>();
        }
    
        public int Booking_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Room_ID { get; set; }
        public Nullable<int> Booking_adults { get; set; }
        public Nullable<int> Booking_kids { get; set; }
        public Nullable<System.DateTime> Booking_CheckIN { get; set; }
        public Nullable<System.DateTime> Booking_CheckOUT { get; set; }
        public Nullable<int> Extra_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<additional> additional { get; set; }
        public virtual customer customer { get; set; }
        public virtual room room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
        public virtual extra extra { get; set; }
        public virtual service service { get; set; }
    }
}
